pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage("Prep for per-dir Jenkinsfile") {
             checkout(scm)
            sh 'git clean -fdx'
        }
        stage("Install dependencies"){
            steps{
                sh "npm ci"
            }
        }

        stage("Check Style"){
            steps{
                sh "npm run lint"
            }
        }

        stage("Test"){
            steps{
                sh "npm test"
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                oc project nidkfe-deploy-strategies
                oc start-build greeting-service --follow --wait
                '''                        
            }
        }
    }
}
